name: libcommon
version: 1.92.0
main: aliuly\loader\Main
api: 2.0.0
load: STARTUP

description: aliuly's common library
author: aliuly
website: https://github.com/Muirfield/pocketmine-plugins/tree/master/libcommon

commands:
  libcommon:
    description: Show libcommon version
    usage: "/libcommon"
    aliases: [lc]
    permission: libcommon.command

permissions:
  libcommon.command:
    default: true
    description: "libcommon command"
